import chalk from "chalk";

console.log(chalk.blue("Raphaël"));
console.log(chalk.red("Florian"));
console.log(chalk.green("Antoine"));
console.log(chalk.yellow("Mahdi"));
console.log(chalk.magenta("Cassiopée"));
console.log(chalk.cyan("Nelia"));
console.log(chalk.white("Victor"));
console.log(chalk.gray("Mathieu"));
console.log(chalk.italic("Marie"));
console.log(chalk.bgBlue("Fred"));
console.log(chalk.bgRed("Leslie"));
console.log(chalk.bgGreen("Claire"));
console.log(chalk.bgYellow("Nassime"));
console.log(chalk.bgMagenta("Sylvain"));
console.log(chalk.bgCyan("Benoit"));
console.log(chalk.bgWhite("David"));
console.log(chalk.bgGray("Victor"));
console.log(chalk.dim("Adam"));
console.log(chalk.bold("Aurore"));
console.log(chalk.underline("Cédric"));
console.log(chalk.inverse("Lucas"));
